require("jake.plugins-setup")
require("jake.core.options")
require("jake.core.keymaps")
require("jake.core.colorscheme")
require("jake.plugins.comment")
require("jake.plugins.nvim-tree")
require("jake.plugins.lualine")
require("jake.plugins.telescope")
